# Generated by Django 3.1.7 on 2021-12-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('user_id_follows_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('follows', models.CharField(max_length=255)),
                ('follows_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('twitter_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('follows_processed_time', models.DateTimeField(null=True)),
                ('track_followers', models.BooleanField(default=False)),
                ('profile_image_url', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('discord', models.TextField(null=True)),
                ('profile_created_at', models.DateTimeField(null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('tweet_count', models.IntegerField(null=True)),
                ('listed_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='twitteraccount',
            index=models.Index(fields=['twitter_id'], name='twitter_tra_twitter_cdb8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='twitteraccount',
            index=models.Index(fields=['username'], name='twitter_tra_usernam_ca2b27_idx'),
        ),
        migrations.AddIndex(
            model_name='follows',
            index=models.Index(fields=['user_id_follows_id'], name='twitter_tra_user_id_8562d9_idx'),
        ),
    ]
