# Generated by Django 3.1.7 on 2022-01-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='follows',
            new_name='followed_user_id',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='user_id',
            new_name='follower',
        ),
    ]
