# Generated by Django 3.1.7 on 2022-01-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_tracker', '0002_auto_20220102_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='follower',
            new_name='follower_id',
        ),
    ]
